config/routes.rb
Rails.application.routes.draw do
  root 'listing#index'

  resources :charges

  resources :jobs do
    collection do
      get :search
    end
  end

  resources :categories do
    resources :jobs
  end
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  validates :name, presence: true
  has_many :jobs

  def to_param
    "#{id} #{name}".parameterize
  end
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id           :integer          not null, primary key
#  title        :string
#  description  :string
#  price        :integer          default("100")
#  location     :string
#  contact      :string
#  company_name :string
#  url          :string
#  email        :string
#  highlight    :boolean          default("f")
#  valid_time   :datetime
#  total_price  :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  category_id  :integer
#  is_active    :boolean          default("f")
#  latitude     :float
#  longitude    :float
#
require 'elasticsearch/model'


class Job < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  belongs_to :category
  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :title, presence: true, length: {within: 3..100}
  validates :description, presence: true, length: {within: 3..1000}
  validates :location, presence: true, length: {within: 3..100}
  validates :contact, presence: true, length: {within: 3..100}
  validates :company_name, presence: true, length: {within: 3..100}
  validates :url, presence: true, length: {maximum: 200}
  validates :email, presence: true,
            length: {maximum: 100},
            format: {with: EMAIL_FORMAT}

  scope :limit_jobs_on, -> (how) {where(is_active: true).limit(how)}
  scope :first_jobs, -> {order('created_at ASC')}

  geocoded_by :location
  after_validation :geocode

  before_save do
    self.email = email.downcase
    set_total_price
  end

  def set_total_price
    if self.highlight
      self.total_price = self.price + 50
    else
      self.total_price = self.price
    end
  end

  def price_in_cents
    total_price * 100
  end

  def to_param
    "#{id} #{title}".parameterize
  end

  def job_location
    "#{self.latitude}, #{self.longitude}"
  end

  def self.search(query)
    __elasticsearch__.search(
        {
            query: {
                multi_match: {
                    query: query,
                    fields: ['title^10', 'description']
                }
            }
        }
    )
  end

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :title, analyzer: 'english'
      indexes :description, analyzer: 'english'
    end
  end
end
Job.import

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @job = Job.find(params[:job_id])
  end

  def create
    @job = Job.find(params[:job])
    customer = Stripe::Customer.create(
        :email => @job.email,
        :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @job.price_in_cents,
        :description => @job.title,
        :currency    => 'eur'
    )
      @job.is_active = true
      @job.save
       UserInvoice.recipe_email(@job).deliver_now
      #SendEmailJob.set(wait: 10.seconds).perform_later(@job)
  rescue Stripe::CardError => e
    @job = Job.find(@job.id)
    @job.is_active=false
    @job.save
    flash[:error] = e.message
    redirect_to edit_job_path(@job)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = Category.find(params[:category_id]).jobs.where(is_active: true).page(params[:page] || 1)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to @job
    else
      render :new
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = Job.find(params[:id])
    redirect_to show if @job.is_active
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to @job
    else
      render :edit
    end
  end

  def search
    if params[:term]
      @jobs = Job.search(params[:term])
    else
      @jobs = Job.all
    end
  end

  private

  def job_params
    params.require(:job).permit(:title,
                                :description,
                                :location,
                                :category_id,
                                :contact,
                                :company_name,
                                :url,
                                :highlight,
                                :email)
  end
end

app/controllers/listing_controller.rb
class ListingController < ApplicationController
  def index
    @categories_jobs = Category.joins(:jobs).where({jobs:{is_active: true}}).group('category_id')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= @job.price_in_cents %></strong>!</h2>

app/views/charges/new.html.erb
<%= @job.inspect %>
<%= form_tag charges_path do %>
    <%= hidden_field_tag :job, @job.id %>
    <article>
      <label class="amount">
        <span>Amount: $<%=@job.total_price%>.00</span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Job price"
            data-amount="<%= @job.price_in_cents %>"></script>
<% end %>

app/views/jobs/edit.html.erb
<h1>Jobs#new</h1>
<p>Find me in app/views/jobs/new.html.erb</p>
<%= form_for @job do |f| %>
    <div>
      <% if @job.errors.any? %>
          <div>
            <% @job.errors.full_messages.each do |error| %>
                <p>
                  <%= error %>
                </p>
            <% end %>
          </div>
      <% end %>
    </div>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :location %>
      <%= f.text_field :location %>
    </div>
    <div>
      <%= f.label :company_name %>
      <%= f.text_field :company_name %>
    </div>
    <div>
      <% Category.all.each do |c| %>
          <div>
            <%= f.radio_button(:category_id, c.id) %>
            <%= f.label :category_id, c.name %>
          </div>
      <% end %>
    </div>
    <div>
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div>
      <%= f.label :contact %>
      <%= f.text_area :contact %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div class="actions">
      <%= f.label :highlight %>
      <%= f.check_box :highlight %>
    </div>
    <div>
      <%= f.submit "create a new job" %>
    </div>
<% end %>

app/views/jobs/index.html.erb
<%= @jobs.count %>
<% @jobs.each do |c| %>
    <div>
      <%= c.title %>
      <%= link_to c.title, job_path(c, category_id: params[:category_id]) %>
    </div>
<% end %>
<div>
  <%= paginate @jobs %>
</div>

app/views/jobs/new.html.erb
<h1>Jobs#new</h1>
<p>Find me in app/views/jobs/new.html.erb</p>
<%= form_for @job do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :company_name %>
      <%= f.text_field :company_name %>
    </div>
    <div>
      <% Category.all.each do |c| %>
      <div>
        <%= f.radio_button(:category_id, c.id) %>
        <%= f.label :category_id, c.name %>
      </div>
      <% end %>
    </div>
    <div>
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div>
      <%= f.label :contact %>
      <%= f.text_area :contact %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div class="actions">
      <%= f.label :highlight %>
      <%= f.check_box :highlight %>
    </div>
    <div>
      <%= f.submit "create a new job" %>
    </div>
<% end %>

app/views/jobs/search.html.erb
<%= @jobs.inspect %>
<%= @jobs.count %>
<h2>Add listing result here</h2>
<%= @jobs.results.total %>
<% @jobs.results.each do |job| %>
    <ul>
      <%= job.title %>,
      <%= job.email %>,
      <%= job.description %>
    </ul>
    <br>
    <%= link_to job.title, job_path(job.id, category_id: job.category_id) %>
<% end %>

app/views/jobs/show.html.erb
<script>
    function initialize() {
        var myLatlng = new google.maps.LatLng(<%=@job.job_location %>);
        var mapOptions = {
            zoom: 14,
            center: myLatlng
        }
        var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

        var marker = new google.maps.Marker({
            position: myLatlng,
            map: map,
            title: "<%= @job.title %>"
        });
//        TODO escape any kind of bad string. or there are allready escaped
        var infowindow = new google.maps.InfoWindow({
            content: "<%= @job.title %>"
        });

        var marker = new google.maps.Marker({
            position: myLatlng,
            map: map,
            title: 'Uluru (Ayers Rock)'
        });
        google.maps.event.addListener(marker, 'click', function() {
            infowindow.open(map,marker);
        });
    }

    function loadScript() {
        var script = document.createElement('script');
        script.type = 'text/javascript';
        script.src = 'https://maps.googleapis.com/maps/api/js?v=3.exp' +
        '&signed_in=true&callback=initialize';
        document.body.appendChild(script);
    }

    //    google.maps.event.addDomListener(window, 'load', initialize);
    window.onload = loadScript;


</script>
<style>
    html, body, #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
    }

    #map-canvas {
        width: 100%;
        height: 500px;
    }
</style>

<div id="map-canvas"></div>

<div>
  <%= @job.inspect %>
</div>
<%= link_to 'Pay', new_charge_path(job_id: @job.id) %>

<% unless @job.is_active %>

    <%= link_to 'Change it', edit_job_path(@job) %> or

    <br>
    <%= link_to 'Pay', new_charge_path(job_id: @job.id) %>
<% end %>

<%= link_to 'back to listing', jobs_path(category_id: params[:category_id]) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BerlinJobs</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<article>
  <%= controller_name %> ||
  <%= action_name %>
</article>
<%= yield %>

</body>
</html>

app/views/listing/index.html.erb
<%= form_tag :search_jobs, method: :get do %>
    <%= label_tag :term %>
    <%= text_field_tag :term %>
    <%= submit_tag 'search for jobs' %>
<% end %>

<% @categories_jobs.each do |c| %>
    <%= c.jobs.count %>
    <strong>
      <%= c.name %>
      <%= link_to c.name, category_jobs_path(c) %>

    </strong>
    <br>
    <% c.jobs.limit_jobs_on(10).first_jobs.each do |job| %>
        <br>
        <%= job.title %>
    <%end %>
    <br>
<% end %>